apiVersion: v1
kind: ReplicationController
metadata:
  name: login03
spec:
  replicas: 2
  selector:
    app: login03
  template:
    metadata:
      name: login03
      labels:
        app: login03
    spec:
      containers:
        - name: login03
          image: harshitameshram/k8s_objects:v3
          ports:
            - containerPort: 80
